### ISSUE TITLE
Invalid default ignore settings

### ISSUE THREAD

**Issue by romuald** [wistful/SublimeAutoPEP8#35]
It seems that the default settings for "ignore" are invalid:

```json
{
    "ignore": "E24, E226",
}
```

*autopep8* does not trim the white spaces between codes, so only E24 is actually ignored

Possible fixes:

- either change the default configuration to remove white spaces
- of patch *autopep8* to trim each code:

```python
def _split_comma_separated(string):
    """Return a set of strings."""
    # before: return set(filter(None, string.split(',')))
    return set(map(unicode.strip, filter(None, string.split(','))))
```

**Comment by wistful** [comment]
Fixed in v1.3
