### ISSUE TITLE
Format on save adding lines to file

### ISSUE THREAD

**Issue by luizpericolo** [wistful/SublimeAutoPEP8#40]
When I save a file and the code is formatted, the plugin adds some characters to the end of the file, usually some part of the last line of the file. 

The above code is PEP8 complient: 

    def increment(val, offset):
        return val += offset
    if __name__ == '__main__':
        a = increment(10, 1)

If, for instance, I forget to add spaces between the compound additive operator and any of the variables and save the file, autopep8 swoops to the rescue, but produces the following code:

    def increment(val, offset):
        return val += offset

    if __name__ == '__main__':
        a = increment(10, 1)
    )

Notice the closing parentheses added to the last line of the file. It is not always the same character either. Sometimes "(10, 1)" is added or any other part of the content of the last line of the file when it is saved.

**Comment by wistful** [comment]
Fixed in **1.3.3-rc1**

**Comment by luizpericolo** [comment]
How do I install it to sublime?

Atenciosamente,
________________________________
--
Luiz Felipe da Costa Pericolo Barbosa
UFRJ - Ciência da Computação / Computer Science
"Are you suggesting coconuts migrate?"
"Stay hungry. Stay foolish."

**Comment by wistful** [comment]
@luizpericolo, you can install dev versions for specific packages using **install_prereleases** option of Package Control [settings](https://packagecontrol.io/docs/settings):
```json
"install_prereleases":
	[
		"AutoPEP8"
	],
```
After that you can upgrade *AutoPEP8* package to the last development version.

**Comment by luizpericolo** [comment]
Cheers!

**Comment by wistful** [comment]
Fix is included into stable version **1.3.3**.
