### ISSUE TITLE
Can't turn off for single project

### ISSUE THREAD

**Issue by JesseAldridge** [wistful/SublimeAutoPEP8#42]
I'm having trouble turning autopep8 off for a single project.  Below is what my sublime-project file looks like.  I might be doing it wrong.  I'm running Sublime 3.

```
{
    "sublimeautopep8": {
        "max-line-length": 79,
        "format_on_save": false,
        "show_output_panel": false,
        // show Format/Preview menu items only for views
        // with syntax from `syntax_list`
        // value is base filename of the .tmLanguage syntax files
        "syntax_list": ["Python"],
        "file_menu_search_depth": 3  // max depth to search python files
    },
    "folders": [
        {
             "path": "."
        }
    ]
}
```

**Comment by wistful** [comment]
Hi @JesseAldridge !

Could you please set _"debug": true_ in you AutoPep8 settings and try to run the extension one more time.
Please attach non-sensitive information from the editor console (hotkey to open console is ⌃ + `) to the issue.

**Comment by JesseAldridge** [comment]
Sorry dude.  I'm not using the extension anymore.
