### ISSUE TITLE
how to disable W191

### ISSUE THREAD

**Issue by goace** [wistful/SublimeAutoPEP8#43]
I don't want autopep8 to change the tab to white space, I add "ignore": "W191", in settings but it doesn't work.

**Comment by wistful** [comment]
Please add W191,E101,E111 to the ignore list.
You can find more information here: https://github.com/hhatto/autopep8/issues/207

**Comment by goace** [comment]
@wistful  Thanks man, it works.

**Comment by yatahaze** [comment]
No luck with this. It only partially uses tabs. [Screenshot](https://i.imgur.com/KdpkhFZ.png)
