### ISSUE TITLE
Can't find AutoPEP8 in the command palette

### ISSUE THREAD

**Issue by egorf** [wistful/SublimeAutoPEP8#45]
Hi!

Something went wrong and I can't seem to run the extension for command palette. Settings are still available through the palette and I can use AutoPEP8 by right-clicking files in the Folders menu on the left.

The editor is build 3114, Mac OS X. 

Thanks!

**Comment by flinz** [comment]
Same here. Build 3126 on OSX.

**Comment by wistful** [comment]
Hi @egorf and @flinz!
Thanks for reporting the issue.
Could you please set *"debug": true* in you AutoPep8 settings and  try to run the extension one more time.
Please attach non-sensitive information from the editor console (hotkey to open console is ⌃ + `) to the bug.

**Comment by flinz** [comment]
@wistful sure.
[Here's the startup log](https://github.com/wistful/SublimeAutoPEP8/files/870711/startup.txt) with ``debug: true``
The final lines get added when i try to find it in the command palette.

**Comment by wistful** [comment]
Thanks for sending the logs.
Unfortunately, there is no plugin debug output there.
It should look like:
```
AutoPEP8:
	sublime: version=3126, platform=linux, arch=x64, packages_path=/home/developer/.config/sublime-text-3/Packages
, installed_packages_path=/home/developer/.config/sublime-text-3/Installed Packages
	plugin: version=1.3.4
	config: {'format_on_save': False, 'select': '', 'debug': True, 'syntax_list': ['Python'], 'file_menu_search_depth': 3, 'indent-size': 4, 'list-fixes': '', 'max-line-length': 79, 'avoid_new_line_in_select_mode': False, 'ignore': ''}
```
Which SublimeAutoPEP8 version are you using?

**Comment by wistful** [comment]
@flinz, please reopen the issue if it still reproducible with current version.

**Comment by jmiguelv** [comment]
I am seeing this issue with build 3176 on OSX.

The output from the log with `debug: true`:
```
AutoPEP8:
	sublime:
	    version=3176
	    platform=osx
	    arch=x64
	    packages_path=/Users/jvieira/Library/Application Support/Sublime Text 3/Packages
	    installed_packages_path=/Users/jvieira/Library/Application Support/Sublime Text 3/Installed Packages
	plugin:
	    version=2.1.0
	    config: {'avoid_new_line_in_select_mode': False, 'ignore-local-config': False, 'hang-closing': False, 'logfile': '/Users/jvieira/Desktop/ap8.log', 'format_on_save': False, 'debug': True, 'exclude': None, 'file_menu_search_depth': 3, 'indent-size': 4, 'select': '', 'max-line-length': 79, 'ignore': '', 'syntax_list': ['Python'], 'global-config': ''}
```

[Editor console output](https://github.com/wistful/SublimeAutoPEP8/files/2057666/startup.txt).
