### ISSUE TITLE
Not formatting on save

### ISSUE THREAD

**Issue by navdeepio** [wistful/SublimeAutoPEP8#50]
I've put the `'format_on_save':true` in user settings, have autopep8 package installed, but the plugin is not formatting the code on save.

**Comment by wistful** [comment]
@navdeepio, thanks for reporting the issue.
There was an issue with missing _argparse_ module which affect Sublime Text 2.
The issue was fixed in in new version(v1.3.5) which was just released.
Please let me know if you experiences the issue in v1.3.5.

**Comment by navdeepio** [comment]
@wistful still experiencing the same issue.

**Comment by wistful** [comment]
Could you please enable debug mode in the plugin settings: `"debug": false` and attach debug output from the SublimeText console?
It'd help finding a place the error happened.

**Comment by navdeepio** [comment]
`SublimeLinter: debug mode: off 
SublimeLinter: WARNING: import of pep8 module in pep8 failed, linter will not work with python 3 code 
SublimeLinter: WARNING: pep8 deactivated, cannot locate 'pep8@python' 
2017-04-30 00:36:14,260 - SublimeAutoPEP8:90 - INFO - AutoPEP8:
	sublime: version=3126, platform=linux, arch=x64, packages_path=/home/wtiger/.config/sublime-text-3/Packages
, installed_packages_path=/home/wtiger/.config/sublime-text-3/Installed Packages
	plugin: version=1.3.5
	config: {'list-fixes': '', 'indent-size': 4, 'max-line-length': 79, 'ignore': 'E24, E226', 'file_menu_search_depth': 3, 'select': '', 'format_on_save': True, 'logfile': None, 'debug': True, 'avoid_new_line_in_select_mode': False, 'syntax_list': ['Python']}
INFO:SublimeAutoPEP8:AutoPEP8:
	sublime: version=3126, platform=linux, arch=x64, packages_path=/home/wtiger/.config/sublime-text-3/Packages
, installed_packages_path=/home/wtiger/.config/sublime-text-3/Installed Packages
	plugin: version=1.3.5
	config: {'list-fixes': '', 'indent-size': 4, 'max-line-length': 79, 'ignore': 'E24, E226', 'file_menu_search_depth': 3, 'select': '', 'format_on_save': True, 'logfile': None, 'debug': True, 'avoid_new_line_in_select_mode': False, 'syntax_list': ['Python']}
Package Control: Skipping automatic upgrade, last run at 2017-04-30 00:33:55, next run at 2017-04-30 01:33:55 or after
`

**Comment by wistful** [comment]
Sorry, certainly "debug": true.
Settings show that the plugin should format code on save event.
However, there are no records about formatting.
Was there any other autopep8 related records in the log after you save a module?
Example of such records:
autopep8.params: Namespace(aggressive=0, diff=True, exclude=[], experimental=False, files=['fake-file'], global_config='fake_path', ignore={'E24'}, ignore_local_config=True, in_place=False, indent_size=4, jobs=1, line_range=None, list_fixes=False, max_line_length=79, pep8_passes=-1, recursive=False, select='', verbose=2)
