### ISSUE TITLE
Max line length setting is ignored

### ISSUE THREAD

**Issue by MHLut** [wistful/SublimeAutoPEP8#55]
I'm using a custom max line length of 119 to format my code. As of a recent update (I cannot with certainty tell you when this happened, but I think it worked fine earlier this week), it appears that this setting is being ignored.

When I use the autoformatter, the formatting is done as if the value of "max-line-length" is 79, which is the default value for this setting.

Is this an issue that other people have as well?

**Specs:**
- OS version: macOS Sierra, `10.12.6`
- Package version: `2.0.0`
- Build: `3156` (Dev Channel).
- User settings (`~/Library/Application Support/Sublime Text 3/Packages/User/AutoPep8.sublime-settings`):

```
{
    "max-line-length": 119
}
```

**Comment by MHLut** [comment]
Addendum: This bug is also present in a stable version of ST3 (build `3143`).

**Comment by wtgee** [comment]
Confirm this is the same on linux distribution with recent package version. This worked previously, maybe early December (sorry, don't have a version number) but I think has not been working for a number of weeks.

**Comment by wistful** [comment]
Fixed in 2.1.0.
