### ISSUE TITLE
E305 expected 2 blank lines after class or function definition

### ISSUE THREAD

**Issue by brupelo** [wistful/SublimeAutoPEP8#58]
Try running your plugin with the below file:

    def foo():
        print('foo')

    if __name__ == "__main__":
        a = 1 + 1
        print('bar')

For some reason you'll still get the next error `x.py:4:1: E305 expected 2 blank lines after class or function definition, found 1` when checking with flake8.

Any idea why autopep8 isn't adding 2 blank lines after 2nd line `print('foo')`?

NS: When trying manually running `autopep8 1.3.4 (pycodestyle: 2.3.1)` on that file it will work ok though.

Thanks.

**Comment by wistful** [comment]
Not reproducible.
