### ISSUE TITLE
AutoPEP8 format command not available in command palette

### ISSUE THREAD

**Issue by jmiguelv** [wistful/SublimeAutoPEP8#60]
Hi,

The AutoPEP8 format command is not available from the command palette. It work in the sidebar only. I am seeing this issue with Sublime Text build 3176 on OSX.

The output from the log with `debug: true`:
```
AutoPEP8:
	sublime:
	    version=3176
	    platform=osx
	    arch=x64
	    packages_path=/Users/jvieira/Library/Application Support/Sublime Text 3/Packages
	    installed_packages_path=/Users/jvieira/Library/Application Support/Sublime Text 3/Installed Packages
	plugin:
	    version=2.1.0
	    config: {'avoid_new_line_in_select_mode': False, 'ignore-local-config': False, 'hang-closing': False, 'logfile': '/Users/jvieira/Desktop/ap8.log', 'format_on_save': False, 'debug': True, 'exclude': None, 'file_menu_search_depth': 3, 'indent-size': 4, 'select': '', 'max-line-length': 79, 'ignore': '', 'syntax_list': ['Python'], 'global-config': ''}
```

[Editor console output](https://github.com/wistful/SublimeAutoPEP8/files/2057666/startup.txt).

**Comment by wistful** [comment]
@jmiguelv, could you please attach `/Users/jvieira/Desktop/ap8.log`?
Debug output was printed to this file.

**Comment by jmiguelv** [comment]
@wistful, the issue no longer applies with the latest versions of the software.
