### ISSUE TITLE
Sublime Text 4 - No Support

### ISSUE THREAD

**Issue by elvirmuslic** [wistful/SublimeAutoPEP8#69]
What is the issue with Sublime Text 4? 
It should be backward compatible with previous versions. 

Any updates?

**Comment by wistful** [comment]
The package is not actively maintained right now, and I can't promise I'll look into that.
However, I'm open to PRs with new features and bug fixes. Contributions and help are very welcome.

**Comment by elvirmuslic** [comment]
I just have no idea what the issue is, I haven't gotten any error messages.

If you let me know where to start or propose a working solution I will look
into fixing it.

Thank you
